#!/bin/bash

function foo()
{
	tput bold
	tput setaf $2
	echo $1
	tput sgr 0
	return 0
}
i


clear
lo="$(date)"
foo  "Access Time: $lo" 2
foo "Welcome $USER, we hope you are doing well!" 4
printf "\n"
foo "WHO IS THERE?" 2
echo "---------------------------------------------------------------------------------------"
who | cut -d ' ' -f 1| uniq
echo "---------------------------------------------------------------------------------------"
printf "\n"
foo "Process Report...." 2
echo "---------------------------------------------------------------------------------------"
top -l 1 -s 0 | grep Phys
top -l 1 -s 0 | grep "CPU usage"
top -U $USER -l 1 -s 0 | grep Process
echo "---------------------------------------------------------------------------------------"
printf "\n"
foo "Hard Disk Summary...." 2
echo "---------------------------------------------------------------------------------------"
df | tr -s " " | cut -d ' ' -f 3 > file1.txt
input="file1.txt"
ctr=1
user=0
while IFS= read -r var
do
  if [ $ctr -eq 1 ] 
  then 
	ctr=$(( $ctr + 1 ))
  else
	ctr=$(( $ctr + 1 ))
	user=$(( $user + $var ))
  fi
done < "$input"

df | tr -s " " | cut -d ' ' -f 4 > file2.txt
input2="file2.txt"
ctr2=1
total=0
while IFS= read -r var
do
  if [ $ctr2 -eq 1 ]
  then
        ctr2=$(( $ctr2 + 1 ))
  else
        ctr2=$(( $ctr2 + 1 ))
        total=$(( $total + $var ))
  fi
done < "$input2"
avail=$total
tot=$(( $avail + $user ))
perfree=$(( $avail * 100  / $tot )) 
peruse=$(( 100 - $perfree ))
#df -h
echo "Percentage Space Used : $peruse%"
echo "Percentage Space Free : $perfree%"
echo "---------------------------------------------------------------------------------------"
printf "\n\n"
foo  "-------------------------------ENJOY YOUR SESSION--------------------------------------" 4
printf "\n\n"
